//! Exporter: ProjectTruth → Markdown | DataFrame → Excel
//!
//! **Mission 031: The Final Export**
//! - Markdown: Forensic Legal Dossier (SHA-256, Lineage)
//! - Excel: Work Tool (Freeze Panes, Auto-fit, Status Column)

use iron_table::{EncodingStatus, ProjectStatus, ProjectTruth, TableTruth};
use polars::prelude::*;
use rust_xlsxwriter::{Color, Format, FormatBorder, Workbook, XlsxError};

/// Markdown Exporter
pub struct MarkdownExporter;

impl MarkdownExporter {
    /// Export ProjectTruth to a legal-grade Markdown dossier.
    pub fn export(truth: &ProjectTruth) -> String {
        let mut md = String::new();

        // 1. Legal Header
        md.push_str("# TACHFILETO: PROJECT TRUTH DOSSIER\n\n");
        md.push_str("> [!IMPORTANT]\n");
        md.push_str("> **GENERATED BY TACHFILETO CORE V1.0**\n");
        md.push_str("> **SOURCE OF TRUTH – DO NOT EDIT MANUALLY**\n\n");

        md.push_str(&format!("- **Project Name**: {}\n", truth.project_name));
        md.push_str(&format!("- **Timestamp**: {}\n", truth.last_updated));
        md.push_str("- **Status**: ");
        match truth.project_status {
            ProjectStatus::Safe => md.push_str("✅ SAFE (XANH)\n"),
            ProjectStatus::Warning => md.push_str("⚠️ WARNING (VÀNG)\n"),
            ProjectStatus::Critical => md.push_str("🚫 CRITICAL (ĐỎ)\n"),
        }
        md.push_str(&format!("- **Reason**: {}\n\n", truth.status_reason));

        // 2. Forensic Seals (SHA-256)
        md.push_str("## 🛡️ FORENSIC SEALS\n\n");
        md.push_str("| Component | Identity / SHA-256 Hash |\n");
        md.push_str("| :--- | :--- |\n");
        md.push_str(&format!("| Project ID | `{}` |\n", truth.project_name)); // Simplified for now
        md.push_str("| Engine | `iron_engine_v1.0_deterministic` |\n\n");

        // 3. Financial Summary
        md.push_str("## 📊 FINANCIAL SUMMARY\n\n");
        md.push_str("| Metric | Value (VND) |\n");
        md.push_str("| :--- | :--- |\n");
        md.push_str(&format!(
            "| **Total Cost** | {:.2} |\n",
            truth.financials.total_cost
        ));
        md.push_str(&format!(
            "| **Total Paid** | {:.2} |\n",
            truth.financials.total_paid
        ));
        md.push_str(&format!(
            "| **Remaining** | {:.2} |\n",
            truth.financials.remaining
        ));
        md.push_str(&format!(
            "| **Deviation** | {:+.2}% |\n\n",
            truth.deviation.percentage
        ));

        // 4. Lineage & Evidence
        md.push_str("## 🔍 LINEAGE & EVIDENCE\n\n");
        md.push_str("This section maps aggregated metrics back to their validated sources.\n\n");

        for (metric, entries) in &truth.lineage {
            md.push_str(&format!("### Metric: `{}`\n\n", metric));
            md.push_str("| Source Table | Row | Col | Contribution |\n");
            md.push_str("| :--- | :--- | :--- | :--- |\n");
            for entry in entries {
                md.push_str(&format!(
                    "| `{}` | {} | {} | {:.2} |\n",
                    entry.source_table, entry.row_idx, entry.col_idx, entry.contribution
                ));
            }
            md.push_str("\n");
        }

        md.push_str("---\n");
        md.push_str("*Audit generated by TachFileTo. Deterministic Integrity Guaranteed.*\n");
        md.push_str("© 2026 DT Building Ecosystem.\n");

        md
    }
}

/// Excel Exporter
pub struct ExcelExporter;

impl ExcelExporter {
    /// Export a Polars DataFrame to a high-fidelity Excel file.
    pub fn export(
        df: &DataFrame,
        table_meta: &TableTruth,
    ) -> std::result::Result<Vec<u8>, XlsxError> {
        let mut workbook = Workbook::new();
        let worksheet = workbook.add_worksheet();

        // Formats
        let header_format = Format::new()
            .set_bold()
            .set_background_color(Color::RGB(0xD9EAD3)) // Light green
            .set_border(FormatBorder::Thin);

        let warning_format = Format::new().set_font_color(Color::Red);

        // 1. Write Headers
        let col_names = df.get_column_names();
        for (col_idx, name) in col_names.iter().enumerate() {
            worksheet.write_with_format(0, col_idx as u16, name.as_str(), &header_format)?;
        }

        // Add Verdict Column Header
        let verdict_col_idx = col_names.len() as u16;
        worksheet.write_with_format(0, verdict_col_idx, "TACHFILETO_VERDICT", &header_format)?;

        // 2. Write Data
        for row_idx in 0..df.height() {
            for (col_idx, col) in df.get_columns().iter().enumerate() {
                let val = col
                    .get(row_idx)
                    .map_err(|e| XlsxError::ParameterError(format!("Polars error: {}", e)))?;

                let excel_row = (row_idx + 1) as u32;
                let excel_col = col_idx as u16;

                match val {
                    AnyValue::Int64(v) => worksheet.write_number(excel_row, excel_col, v as f64)?,
                    AnyValue::Int32(v) => worksheet.write_number(excel_row, excel_col, v as f64)?,
                    AnyValue::UInt64(v) => {
                        worksheet.write_number(excel_row, excel_col, v as f64)?
                    }
                    AnyValue::UInt32(v) => {
                        worksheet.write_number(excel_row, excel_col, v as f64)?
                    }
                    AnyValue::Float64(v) => worksheet.write_number(excel_row, excel_col, v)?,
                    AnyValue::Float32(v) => {
                        worksheet.write_number(excel_row, excel_col, v as f64)?
                    }
                    AnyValue::String(s) => worksheet.write_string(excel_row, excel_col, s)?,
                    AnyValue::Boolean(b) => worksheet.write_boolean(excel_row, excel_col, b)?,
                    AnyValue::Null => worksheet.write_string(excel_row, excel_col, "")?,
                    _ => worksheet.write_string(excel_row, excel_col, &format!("{}", val))?,
                };
            }

            // 3. Write Verdict (Status)
            if let Some(row_meta) = table_meta.rows.get(row_idx) {
                // Determine row-level status
                let is_rejected = row_meta
                    .cells
                    .iter()
                    .any(|c| matches!(c.encoding_status, EncodingStatus::Invalid));
                let is_suspicious = row_meta
                    .cells
                    .iter()
                    .any(|c| matches!(c.encoding_status, EncodingStatus::Suspicious));

                let (status_text, format) = if is_rejected {
                    ("REJECTED", Some(&warning_format))
                } else if is_suspicious {
                    ("SUSPICIOUS", None)
                } else {
                    ("CLEAN", None)
                };

                if let Some(f) = format {
                    worksheet.write_with_format(
                        (row_idx + 1) as u32,
                        verdict_col_idx,
                        status_text,
                        f,
                    )?;
                } else {
                    worksheet.write_string((row_idx + 1) as u32, verdict_col_idx, status_text)?;
                }
            }
        }

        // 4. Elite Formatting
        worksheet.set_freeze_panes(1, 0)?; // Freeze Header
        worksheet.autofit(); // Auto-fit all columns

        // Metadata: Embed Project ID in properties
        workbook.set_properties(
            &rust_xlsxwriter::DocProperties::new()
                .set_author("TachFileTo Engine")
                .set_title(&format!("Truth Export: {}", table_meta.table_id))
                .set_comment("Deterministic audit export by TachFileTo."),
        );

        workbook.save_to_buffer()
    }
}
